name: recibot
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.1=pyhcf101f3_0
  - blinker=1.9.0=pyhff2d567_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - distro=1.9.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - flask=2.3.3=pyhd8ed1ab_0
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jiter=0.13.0=py312h0ccc70a_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgomp=15.2.0=he0feb66_17
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_17
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - markupsafe=3.0.3=py312h8a5da7c_0
  - ncurses=6.5=h2d0b736_3
  - openai=2.20.0=pyhd8ed1ab_0
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0.1=pyh8b19718_0
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py312h868fb18_1
  - python=3.12.3=hab00c5b_0_cpython
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python_abi=3.12=8_cp312
  - readline=8.3=h853b02a_0
  - setuptools=82.0.0=pyh332efcf_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - tk=8.6.13=noxft_h366c992_103
  - tqdm=4.67.3=pyh8f84b5b_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - werkzeug=3.1.5=pyhcf101f3_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - zipp=3.23.0=pyhcf101f3_1
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/lenovo/miniconda3/envs/recibot
